
DROP TABLE PRECIO_PINATA				;
DROP TABLE USUARIOS_SISTEMA				;
DROP TABLE ARTESANOS;                   
DROP TABLE ARTESANOS_PEDIDOS			;
DROP TABLE PEDIDO_PINATA				;

DROP TABLE CATALOGO_CLIENTES			;
DROP TABLE CATALOGO_EMPLEADOS			;
DROP TABLE CATALOGO_EMPLEADOS_PUESTOS	;

DROP TABLE CATALOGO_PEDIDO_ESTATUS		;
DROP TABLE CATALOGO_PROVEEDORES			;
DROP TABLE CATALOGO_TIPO_PINATA			;
DROP TABLE CATALOGO_CIUDADES			;
DROP TABLE CATALOGO_ESTADOS				;
DROP TABLE CATALOGO_PAISES				;
