SELECT * FROM CATALOGO_PAISES;
SELECT * FROM CATALOGO_ESTADOS;
SELECT * FROM CATALOGO_CIUDADES;


SELECT * FROM PRECIO_PINATA PP
JOIN CATALOGO_TIPO_PINATA CTP
	ON PP.ctpinCodigo = CTP.ctpinCodigo

SELECT * FROM CATALOGO_CLIENTES;

SELECT * FROM PEDIDO_PINATA;

SELECT * FROM v_CLIENTES;

SELECT * FROM v_PROVEEDORES;

SELECT * FROM v_PRECIO_PINATA;

SELECT * FROM v_COTIZACIONES;

SELECT * FROM v_GESTOR_GANANCIAS;

SELECT * FROM v_VISOR_CARGA_TRABAJO;

SELECT * FROM v_ASIGNACION_TRABAJO_ARTESANOS;

SELECT * FROM v_ASIGNACION_TRABAJO_PEDIDOS_ESPERANDO;


